version: '2'

services:
  ddns:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/ddns/Dockerfile
    depends_on:
      - redis
    environment:
      DDNS_DOMAIN: dyndns.andres.one
      DDNS_SOA_DOMAIN: dyndns.andres.one
      DDNS_REDIS_HOST: redis:6379
    ports:
      - 8083:8080

  powerdns:
    restart: unless-stopped
    build:
      context: powerdns/
      dockerfile: Dockerfile
    depends_on:
      - ddns
    environment:
      PDNS_REMOTE_HTTP_HOST: "ddns:8053"
    ports:
      - 53:53/udp

  redis:
    restart: unless-stopped
    image: redis:4-alpine
    volumes:
      - "${PWD}/.redis_mount:/data"

